
const constantes = {
  // TIPOS DE MEDIO
  TIPO_MEDIO_TV: 1,
  TIPO_MEDIO_RADIO: 2,
  TIPO_MEDIO_PRENSA: 3,
  TIPO_MEDIO_RADIO_FM: 4,
  TIPO_MEDIO_RADIO_AM: 5,
  TIPO_MEDIO_PROD_IND_TV: 6,
  TIPO_MEDIO_PROD_IND_RADIO_FM: 7,
  TIPO_MEDIO_PROD_IND_RADIO_AM: 8,
  // AFPS
  AFP_PREVISION: 9,
  AFP_FUTURO: 10,
  // NIVEL DE DPA
  NIVEL_DPA_DEPARTAMENTO: 2,
  NIVEL_DPA_PROVINCIA: 3,
  NIVEL_DPA_MUNICIPIO: 4,
  // TIPOS DE cobertura
  COBERTURA_NACIONAL: 'NACIONAL',
  COBERTURA_DEPARTAMENTAL: 'DEPARTAMENTAL',
  COBERTURA_PROVINCIAL: 'PROVINCIAL',
  COBERTURA_MUNICIPAL: 'MUNICIPAL',
  // ROLES
  ROL_SUPERADMIN: 1,
  ROL_ADMIN: 2,
  ROL_TECNICO: 3,
  ROL_JEFE: 4,
  ROL_MEDIO: 5,
  // ESTADO
  ESTADO_NUEVO: 'NUEVO',
  ESTADO_CREADO: 'CREADO',
  ESTADO_APROBADO: 'APROBADO',
  ESTADO_OBSERVADO: 'OBSERVADO',
  ESTADO_RECHAZADO: 'RECHAZADO',
  ESTADO_EN_CURSO: 'EN_CURSO',
  ESTADO_GENERADO: 'GENERADO',
  // PLANTILLA
  PLANTILLA_REGISTRO_MEDIO: 1,
  PLANTILLA_RECORDATORIO_AFPS: 2,
  PLANTILLA_RECHAZO_MEDIO: 3
};

module.exports = {
  constantes
};
